Document: libpam-pico
Title: Debian libpam-pico Manual
Author: <insert document author here>
Abstract: This manual describes what libpam-pico is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libpam-pico/libpam-pico.sgml.gz

Format: postscript
Files: /usr/share/doc/libpam-pico/libpam-pico.ps.gz

Format: text
Files: /usr/share/doc/libpam-pico/libpam-pico.text.gz

Format: HTML
Index: /usr/share/doc/libpam-pico/html/index.html
Files: /usr/share/doc/libpam-pico/html/*.html
